apiVersion: v1
kind: Service
metadata:
  name: cs-notification-service
spec:
  selector:
    app: cs-notification-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  