apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-post-service
  labels:
    app: cs-post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-post-service
  template:
    metadata:
      name: cs-post-service
      labels:
        app: cs-post-service
    spec:
      containers:
        - name: cs-post-service
          image: vadimkirpikov/cs-post-service
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
      restartPolicy: Always
      