apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kafka
  labels:
    app: test-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-kafka
  template:
    metadata:
      labels:
        app: test-kafka
    spec:
      containers:
        - name: test-kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://test-kafka:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG4J_OPTS
              value: "-Dlog4j.rootLogger=TRACE,stdout"
            - name: LOG_DIR
              value: "/var/log/kafka"