apiVersion: v1
kind: Service
metadata:
  name: test-kafka
  labels:
    app: test-kafka
spec:
  selector:
    app: test-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP