apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-db
  labels:
    app: notification-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      name: notification-db
      labels:
        app: notification-db
    spec:
      containers:
        - name: notification-db
          image: postgres:17.2
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "notification-db"
            - name: POSTGRES_PASSWORD
              value: "123"
      restartPolicy: Always
      